version: '3'
services:
    cmcut:
      container_name: cmcut
      build: .
      devices:
       - /dev/dri/renderD128
      volumes:
        - ${INPUT_DIR_PATH}:/ts
        - ${OUTPUT_DIR_PATH}:/mp4
        - ./logo:/root/JoinLogoScpTrialSetLinux/modules/join_logo_scp_trial/logo
      tty: true
      restart: unless-stopped
